--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaDevGuy/MCPEToConsole
build-by-default: true
branches:
- main
projects:
  MCPEToConsole:
    path: ""
    icon: "assets/images/icon.png"
...
