name: MCPEtoConsole
author: DaDevGuy
main: MCPEtoConsole\DaDevGuy\Main
api: 5.3.0
version: 2.1.0

permissions:
 mcpetoconsole.cmd:
  description: Allows the use of the /console command
  default: op
