name: MCPEtoConsole
author: DaDevGuy
main: MCPEtoConsole\DaDevGuy\Main
api: [4.0.0]
version: 2.0.1

permissions:
 mcpetoconsole.cmd:
  description: Allows the use of the /console command
  default: op
