name: MCPEtoConsole
author: DaDevGuy
main: MCPEtoConsole\DaDevGuy\Main
api: [4.0.0]
version: 2.0.1

commands:
 console:
  description: "Send Commands To Console!"
  permission: mcpetoconsole.cmd
  aliases: ["c"]

permissions:
 mcpetoconsole.cmd:
  default: op
